name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: action/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install epenencies 
        run: pip install flask 
      - name: run Docker build
        run: dcoker build -t devops-porfolio .
